# Custom fields
title: "AskClass Home Theme"
description: >
  Simple reponsive homepage inspired by AskClass landing page.

ach:
  date_format: "%b %d, %y"
  short_name: "AC Home"
  color:
    theme: "#ffc100"
    bg: "#222"
  url: "https://ach.askclass.com"
  categories:
    - education
  social:
    twitter: "askclass_com"
  logo:
    image: "logo.svg"
    size: 200
    alt_image: "logo-icon.svg"
    alt_size: 70
    sizes: [ 48, 96, 144, 192, 300, 512 ]
  meta:
    apple_icon: "logo-300.png"
    og_image: "logo-square-512.png"
    favicon: "favicon.ico"
    keywords: >
      edtech,
      education,
      technology,
      learning,
      teaching,
      student,
      educator,
      university
  font_families:
    - Lora
    - Open+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400;1,700
    - Josefin+Sans
    - Share+Tech+Mono
    - Lexend
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  modules:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "modules"
    values:
      layout: "modules"

sass:
  style: compact

include:
  - index.html
  - 404.html
  - pwabuilder-sw.js
  - content

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - askclass-home-theme.gemspec
  - CNAME
  - runme.sh

